name = "Tecc 3"
author = "MarioAndWeegee3"
version = "0.6.0-beta.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a358fcb18206349747252cddd1950ce89013e690076975c2e738f59fc8ec7235"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
