name = "Tecc 3"
author = "MarioAndWeegee3"
version = "0.6.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e84da8787be6dc83d4f1b6e1a91cebb3902e686126dea34bd99c2b6262e2761"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
