name = "Actually Useful Smithing Table [Fabric]"
filename = "actuallyusefulsmithingtable-0.0.1-1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3723/510/actuallyusefulsmithingtable-0.0.1-1.18.2.jar"
hash-format = "sha1"
hash = "ecbc47d51bb252568ecd2b4b5a404d8bbc919120"

[update]
[update.curseforge]
file-id = 3723510
project-id = 568328
