name = "AE2 Things"
filename = "AE2Things-1.0.2-beta.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3717/664/AE2Things-1.0.2-beta.3.jar"
hash-format = "sha1"
hash = "2c2cf151dac800e5fb0d180413cb81bb860ccdce"

[update]
[update.curseforge]
file-id = 3717664
project-id = 563800
