name = "Akashic Tome of Tools Fabric"
filename = "akashictomeoftools-1.2.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3725/836/akashictomeoftools-1.2.1.jar"
hash-format = "sha1"
hash = "c3f0263d1776455fd8d79cdee32f8850f29b1f8d"

[update]
[update.curseforge]
file-id = 3725836
project-id = 544237
