name = "Amplified Nether"
filename = "Amplified_Nether_v1.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3683/373/Amplified_Nether_v1.1.1.jar"
hash-format = "sha1"
hash = "1263318bd15e90d0f3a570d1ddb893edaa2eb49b"

[update]
[update.curseforge]
file-id = 3683373
project-id = 552176
