name = "Applied Energistics 2"
filename = "appliedenergistics2-11.0.0-alpha.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3764/63/appliedenergistics2-11.0.0-alpha.5.jar"
hash-format = "sha1"
hash = "0ac2afec22e1ba537c9fc08505136186027d7dce"

[update]
[update.curseforge]
file-id = 3764063
project-id = 223794
