name = "Applied Energistics 2 Wireless Terminals"
filename = "AE2WTLib-11.0.0-alpha.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3748/906/AE2WTLib-11.0.0-alpha.2.jar"
hash-format = "sha1"
hash = "294b8aa1b8180820c6dbb9eda048dc7e4b9541b3"

[update]
[update.curseforge]
file-id = 3748906
project-id = 459929
