name = "Armor Stand Editor"
filename = "armor-stand-editor-1.3.2+1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3725/750/armor-stand-editor-1.3.2+1.18.2.jar"
hash-format = "sha1"
hash = "0d4131877b77de38fe2e50324945eb09705a779d"

[update]
[update.curseforge]
file-id = 3725750
project-id = 465383
