name = "Armor Stand Editor"
filename = "armor-stand-editor-1.3.1+1.18-rc3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3539/588/armor-stand-editor-1.3.1+1.18-rc3.jar"
hash-format = "sha1"
hash = "7889a617da44608c2dc8a21fe1c5c527b464fbf4"

[update]
[update.curseforge]
file-id = 3539588
project-id = 465383
