name = "BetterClicker"
filename = "better_clicker-2.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3712/702/better_clicker-2.0.0.jar"
hash-format = "sha1"
hash = "779d185d087bbe2697bb82f5a6eede31c7e62965"

[update]
[update.curseforge]
file-id = 3712702
project-id = 565903
