name = "BetterDarkMode"
filename = "betterdarkmode-1.0.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3607/387/betterdarkmode-1.0.4.jar"
hash-format = "sha1"
hash = "d90b6717e7bd7e12632666b09bb15ad983e65369"

[update]
[update.curseforge]
file-id = 3607387
project-id = 537641
