name = "Carpet Extra"
filename = "carpet-extra-1.18-1.4.56.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3542/68/carpet-extra-1.18-1.4.56.jar"
hash-format = "sha1"
hash = "57f63f089436502ac3ae132c4abc475b41bbb2a0"

[update]
[update.curseforge]
file-id = 3542068
project-id = 349240
