name = "Conjuring"
filename = "conjuring-1.0.22+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3693/350/conjuring-1.0.22+1.18.jar"
hash-format = "sha1"
hash = "9669afc5a8264e3c3ab080b6a1e9f3479f54911e"

[update]
[update.curseforge]
file-id = 3693350
project-id = 422310
