name = "Convenient mobGriefing"
filename = "convenient-mobgriefing-2.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3355/80/convenient-mobgriefing-2.0.2.jar"
hash-format = "sha1"
hash = "85f21fd3a8f71dbb669739f4bce5e12eb0578a1f"

[update]
[update.curseforge]
file-id = 3355080
project-id = 374048
