name = "Crafting Tweaks (Fabric Edition)"
filename = "craftingtweaks-fabric-1.18-13.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3545/612/craftingtweaks-fabric-1.18-13.0.0.jar"
hash-format = "sha1"
hash = "44f61d891c2fb968186307719e158aec46217dc2"

[update]
[update.curseforge]
file-id = 3545612
project-id = 502516
