name = "Crooked Crooks"
filename = "crookedcrooks-2.0.1+1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3569/19/crookedcrooks-2.0.1+1.18.1.jar"
hash-format = "sha1"
hash = "d622c12a90c3e591f1ba742abb7358ce3d3c4019"

[update]
[update.curseforge]
file-id = 3569019
project-id = 393714
