name = "Culinaire"
filename = "culinaire-2.3.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3575/39/culinaire-2.3.3.jar"
hash-format = "sha1"
hash = "d0537d61a3c458f707a10538ddd2d8ef189bc1ef"

[update]
[update.curseforge]
file-id = 3575039
project-id = 390675
