name = "Culinaire"
filename = "culinaire-2.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3723/221/culinaire-2.4.0.jar"
hash-format = "sha1"
hash = "02e79b2f3e66bdf6031b88fd60758c66fcdcaf6b"

[update]
[update.curseforge]
file-id = 3723221
project-id = 390675
