name = "Dank Storage Fabric"
filename = "dankstorage-1.18.1-3.5.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3656/602/dankstorage-1.18.1-3.5.3.jar"
hash-format = "sha1"
hash = "1742c6b831e5fc7a1dc17d956819ea233a9c0eff"

[update]
[update.curseforge]
file-id = 3656602
project-id = 400619
