name = "Dank Storage Fabric"
filename = "dankstorage-1.18.2-3.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3681/398/dankstorage-1.18.2-3.6.jar"
hash-format = "sha1"
hash = "f9328b97045cb038208b56d18963d8bdfef4ec3a"

[update]
[update.curseforge]
file-id = 3681398
project-id = 400619
