name = "Dawn API"
filename = "dawn-3.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3575/28/dawn-3.2.0.jar"
hash-format = "sha1"
hash = "84846a6a9ae738a9ba3faf7e552dd844df42c850"

[update]
[update.curseforge]
file-id = 3575028
project-id = 399309
