name = "Dawn API"
filename = "dawn-3.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3722/593/dawn-3.3.0.jar"
hash-format = "sha1"
hash = "e6a97045ec54148d83c2222760360b34362ee374"

[update]
[update.curseforge]
file-id = 3722593
project-id = 399309
