name = "DeepslateCutting"
filename = "deepslatecutting-1.18.1-1.3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3648/247/deepslatecutting-1.18.1-1.3.1.jar"
hash-format = "sha1"
hash = "cac437d1d610bd2b81f03d45cfc5f45031bd1c2b"

[update]
[update.curseforge]
file-id = 3648247
project-id = 504899
