name = "DeepslateCutting"
filename = "deepslatecutting-1.18.2-1.3.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3668/296/deepslatecutting-1.18.2-1.3.2.jar"
hash-format = "sha1"
hash = "ad3131629f130ef5c184ab9fc313c9359baf6cd1"

[update]
[update.curseforge]
file-id = 3668296
project-id = 504899
