name = "Dense Ores: Refabricated"
filename = "denseores-1.2.1+1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3575/472/denseores-1.2.1+1.18.1.jar"
hash-format = "sha1"
hash = "99e1c4944b3a616ae94a749b03ac715f80e686c3"

[update]
[update.curseforge]
file-id = 3575472
project-id = 527045
