name = "Dense Ores: Refabricated"
filename = "denseores-1.2.2+1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3669/946/denseores-1.2.2+1.18.2.jar"
hash-format = "sha1"
hash = "355fcae3b9240c972053bc7e703d8157fb5b75e7"

[update]
[update.curseforge]
file-id = 3669946
project-id = 527045
