name = "Dimension Coordinate Converter"
filename = "dimension-coord-converter-1.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3722/287/dimension-coord-converter-1.1.1.jar"
hash-format = "sha1"
hash = "d9e9800325880f6c7337afcb20323de641c0c30d"

[update]
[update.curseforge]
file-id = 3722287
project-id = 555045
