name = "Double-Tap Dash"
filename = "dash-1.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3684/542/dash-1.2.0.jar"
hash-format = "sha1"
hash = "61f98e9d67895657fce2ae71991ca5ce5a8de1b2"

[update]
[update.curseforge]
file-id = 3684542
project-id = 574205
