name = "Durability Notifier"
filename = "DurabilityNotifier-fabric-1.18.2-1.2.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3761/951/DurabilityNotifier-fabric-1.18.2-1.2.2.jar"
hash-format = "sha1"
hash = "1fa34af0220fd29a3f2da705d4922927a9871f3f"

[update]
[update.curseforge]
file-id = 3761951
project-id = 277095
