name = "More Geodes"
filename = "more-geodes-1.3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3741/45/more-geodes-1.3.1.jar"
hash-format = "sha1"
hash = "6b9f3cf48ab6691cc887c5bab16238b28da701e2"

[update]
[update.curseforge]
file-id = 3741045
project-id = 437712
