name = "Enhanced Searchability"
filename = "EnhancedSearchability-2.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3741/257/EnhancedSearchability-2.0.3.jar"
hash-format = "sha1"
hash = "88d9e66b240f30c4abfb278d7211f8415ea4a91a"

[update]
[update.curseforge]
file-id = 3741257
project-id = 538023
