name = "[Fabric] Expanded Storage"
filename = "expandedstorage-7.3.12+1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3760/350/expandedstorage-7.3.12+1.18.2.jar"
hash-format = "sha1"
hash = "6e269d5bafbd9833a73daa7a3ad24e38f962f1dd"

[update]
[update.curseforge]
file-id = 3760350
project-id = 317856
