name = "EZ Pipes and Stuff (EZPaS)"
filename = "ezpas-2.0.1-1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3583/333/ezpas-2.0.1-1.18.1.jar"
hash-format = "sha1"
hash = "7ecadd7b1943e8f6776e8c6fad5fa12cfbbc0732"

[update]
[update.curseforge]
file-id = 3583333
project-id = 381973
