name = "[FABRIC] Launchpads"
filename = "zihlaunchpads-1.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3673/151/zihlaunchpads-1.2.0.jar"
hash-format = "sha1"
hash = "c4e26527e4926d8eaedc16aef30f37e19dc30709"

[update]
[update.curseforge]
file-id = 3673151
project-id = 521065
