name = "Fabric Craftable Enchanted Golden Apple"
filename = "craftable_enchanted_golden_apple-1.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3575/205/craftable_enchanted_golden_apple-1.0.2.jar"
hash-format = "sha1"
hash = "a8c5b0f73a34e26701819223da5453596136f488"

[update]
[update.curseforge]
file-id = 3575205
project-id = 335918
