name = "FancyMenu [Fabric]"
filename = "fancymenu_fabric_2.6.3_MC_1.18-1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3651/349/fancymenu_fabric_2.6.3_MC_1.18-1.18.1.jar"
hash-format = "sha1"
hash = "75f02e5be2c8499a670ec905fbf7d9d7af2c7c53"

[update]
[update.curseforge]
file-id = 3651349
project-id = 416796
