name = "FastGrowth"
filename = "fastgrowth-1.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3734/174/fastgrowth-1.6.jar"
hash-format = "sha1"
hash = "b7281eb8d35e37d761be359040813758b24d3e28"

[update]
[update.curseforge]
file-id = 3734174
project-id = 403544
