name = "FindMe"
filename = "findme-3.0.6-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3732/921/findme-3.0.6-fabric.jar"
hash-format = "sha1"
hash = "b65e7ac9ab1e5834ebef325f5b84e44ddaf6830e"

[update]
[update.curseforge]
file-id = 3732921
project-id = 291936
