name = "Freecam (Fabric)"
filename = "freecam-1.0.4+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3745/385/freecam-1.0.4+1.18.jar"
hash-format = "sha1"
hash = "1d0d5b9e90ea148d29da612850f198f0f70c7848"

[update]
[update.curseforge]
file-id = 3745385
project-id = 557076
