name = "Golden Hoppers"
filename = "goldenhoppers-1.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3592/2/goldenhoppers-1.2.0.jar"
hash-format = "sha1"
hash = "8a04de2d0fa6115924147f7333d932d00bed6b0b"

[update]
[update.curseforge]
file-id = 3592002
project-id = 442268
