name = "Golden Hoppers"
filename = "goldenhoppers-1.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3753/605/goldenhoppers-1.3.0.jar"
hash-format = "sha1"
hash = "aeb8fa0e9994c0df03215f96e1a406cc72c7c871"

[update]
[update.curseforge]
file-id = 3753605
project-id = 442268
