name = "Homabric"
filename = "homabric-1.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3579/400/homabric-1.1.1.jar"
hash-format = "sha1"
hash = "1ed31b1aafe40c86a8b5b20427a29158183b865e"

[update]
[update.curseforge]
file-id = 3579400
project-id = 558888
