name = "I Know What I'm Doing (IKWID)"
filename = "IKnowWhatImDoing-4.0.0-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3561/96/IKnowWhatImDoing-4.0.0-fabric.jar"
hash-format = "sha1"
hash = "2491000265b8cfc8f7b8a99c98576f1040712bf7"

[update]
[update.curseforge]
file-id = 3561096
project-id = 271492
