name = "Better Command Block Editor - Fabric"
filename = "BetterCmdBlockFabric-1.18.2-2.5.10.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3684/947/BetterCmdBlockFabric-1.18.2-2.5.10.jar"
hash-format = "sha1"
hash = "00c97b6b282e64cce52c648527e706a438568340"

[update]
[update.curseforge]
file-id = 3684947
project-id = 500959
