name = "Iris Shaders"
filename = "iris-mc1.18.2-1.2.3-build.35.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3767/760/iris-mc1.18.2-1.2.3-build.35.jar"
hash-format = "sha1"
hash = "54f32b6beaa5bfb3bbfde8eacd615b2ddcec1fca"

[update]
[update.curseforge]
file-id = 3767760
project-id = 455508
