name = "Leaves Us In Peace"
filename = "leaves-us-in-peace-1.0.4+MC1.18-1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3694/87/leaves-us-in-peace-1.0.4+MC1.18-1.18.2.jar"
hash-format = "sha1"
hash = "853b5c6cf190964e732b0656bbdef8c382170297"

[update]
[update.curseforge]
file-id = 3694087
project-id = 565173
