name = "Lithium (Fabric)"
filename = "lithium-fabric-mc1.18.1-0.7.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3590/908/lithium-fabric-mc1.18.1-0.7.7.jar"
hash-format = "sha1"
hash = "8eaffcb994e67ac7b3fd2efa526f7721f8327d11"

[update]
[update.curseforge]
file-id = 3590908
project-id = 360438
