name = "megane"
filename = "megane-7.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3753/700/megane-7.4.0.jar"
hash-format = "sha1"
hash = "3e2fd115eb4436024fcb6f7237c76b3c9067b642"

[update]
[update.curseforge]
file-id = 3753700
project-id = 408118
