name = "Mining Dimensions [FABRIC]"
filename = "MiningDimensions_Fabric-1.18.2-1.3.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3721/853/MiningDimensions_Fabric-1.18.2-1.3.5.jar"
hash-format = "sha1"
hash = "08bb92709dccca48992dc75876dda0346428d18e"

[update]
[update.curseforge]
file-id = 3721853
project-id = 442921
