name = "Modern Industrialization"
filename = "Modern-Industrialization-1.1.0-alpha.01.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3718/118/Modern-Industrialization-1.1.0-alpha.01.jar"
hash-format = "sha1"
hash = "5dae61d0446a243e314b914b0a7357b880353402"

[update]
[update.curseforge]
file-id = 3718118
project-id = 405388
