name = "Mouse Wheelie (Fabric)"
filename = "mousewheelie-1.8.2+mc1.18-pre5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3654/877/mousewheelie-1.8.2+mc1.18-pre5.jar"
hash-format = "sha1"
hash = "a4e742ee77e40f76af584dd9b2f1595dabfe09e9"

[update]
[update.curseforge]
file-id = 3654877
project-id = 317514
