name = "Nether Wart Block to Nether Warts"
filename = "netherwardblock-1.18.2-2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3735/233/netherwardblock-1.18.2-2.jar"
hash-format = "sha1"
hash = "f3d8cf97bced42a42012e0928e61b17ea7e404a3"

[update]
[update.curseforge]
file-id = 3735233
project-id = 517690
