name = "Nether Wart Block to Nether Warts"
filename = "netherwardblock-1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3574/386/netherwardblock-1.18.1.jar"
hash-format = "sha1"
hash = "17e94e242964dfc6ce6081a476eb807a37556c17"

[update]
[update.curseforge]
file-id = 3574386
project-id = 517690
