name = "Numeral Ping"
filename = "numeralping-1.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3695/293/numeralping-1.0.3.jar"
hash-format = "sha1"
hash = "de09000e93190c2b2b35c5728138144893c2db57"

[update]
[update.curseforge]
file-id = 3695293
project-id = 559653
