name = "Open Loader"
filename = "OpenLoader-Fabric-1.18.1-11.0.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3618/464/OpenLoader-Fabric-1.18.1-11.0.4.jar"
hash-format = "sha1"
hash = "d7ca3d17dba762c255e3f2d4920d9dd9b2799801"

[update]
[update.curseforge]
file-id = 3618464
project-id = 354339
