name = "Origins (Fabric)"
filename = "Origins-1.18.2-1.4.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3752/286/Origins-1.18.2-1.4.1.jar"
hash-format = "sha1"
hash = "696f33de73a4cf35baa347797fdd8dbb26c18541"

[update]
[update.curseforge]
file-id = 3752286
project-id = 391943
