name = "Origins: Classes"
filename = "Origins-Classes-1.18.2-1.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3752/361/Origins-Classes-1.18.2-1.3.0.jar"
hash-format = "sha1"
hash = "3c3c8511dfed2cc38accc1b29703b504d1637e0c"

[update]
[update.curseforge]
file-id = 3752361
project-id = 401833
