name = "Pettable"
filename = "pettable-1.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3757/158/pettable-1.3.0.jar"
hash-format = "sha1"
hash = "68daa08c2b502a5f1f554b869140379be8ad5b34"

[update]
[update.curseforge]
file-id = 3757158
project-id = 468991
