name = "Plushie Mod"
filename = "plushie-mod-1.1-1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3559/945/plushie-mod-1.1-1.18.1.jar"
hash-format = "sha1"
hash = "31e9db21a4772b86f1f02877dc1186013d183742"

[update]
[update.curseforge]
file-id = 3559945
project-id = 544197
