name = "Plushie Mod"
filename = "plushie-mod-1.2-1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3699/524/plushie-mod-1.2-1.18.1.jar"
hash-format = "sha1"
hash = "8cb1420651dbc2f4b81015c9945bfdc99624957c"

[update]
[update.curseforge]
file-id = 3699524
project-id = 544197
