name = "Reinforced Shulker Boxes"
filename = "reinforced-shulker-boxes-2.0.0-beta.2+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3639/985/reinforced-shulker-boxes-2.0.0-beta.2+1.18.jar"
hash-format = "sha1"
hash = "b19e7b04019b96cd0c33041ed991c39b22b7c4d0"

[update]
[update.curseforge]
file-id = 3639985
project-id = 529874
