name = "Server Hats"
filename = "server-hats-0.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3558/586/server-hats-0.8.jar"
hash-format = "sha1"
hash = "e211a16305172acd9e7d62f9ad7b35050badb55c"

[update]
[update.curseforge]
file-id = 3558586
project-id = 549653
