name = "Server Hats"
filename = "server-hats-0.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3667/535/server-hats-0.9.jar"
hash-format = "sha1"
hash = "95b04eede99b76a2975f1fa2aefe61327ca78940"

[update]
[update.curseforge]
file-id = 3667535
project-id = 549653
