name = "Shift-Scroll Fix for macOS [Fabric]"
filename = "shift-scroll-fix-1.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3343/722/shift-scroll-fix-1.0.1.jar"
hash-format = "sha1"
hash = "1baef5da1048bb14c6c82098c1ef52fa1c5d6a6f"

[update]
[update.curseforge]
file-id = 3343722
project-id = 437526
