name = "[FABRIC] Skeleton Aiming Fix"
filename = "skeletonfix-1.1.1+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3575/600/skeletonfix-1.1.1+1.18.jar"
hash-format = "sha1"
hash = "84e4c05309ed6fc45c02212dece45f13d7b0b791"

[update]
[update.curseforge]
file-id = 3575600
project-id = 557897
