name = "Stoneholm, Underground Villages (Fabric)"
filename = "stoneholm-1.4.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3631/590/stoneholm-1.4.2.jar"
hash-format = "sha1"
hash = "c29f7e8fc217b46233f78722831da910799f184e"

[update]
[update.curseforge]
file-id = 3631590
project-id = 460336
