name = "St'ructure Tools"
filename = "structure-tools-1.0.10.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3600/965/structure-tools-1.0.10.jar"
hash-format = "sha1"
hash = "d6950a8e5fe329f0d353c137315c237d893961bc"

[update]
[update.curseforge]
file-id = 3600965
project-id = 536984
