name = "The Bumblezone (Fabric)"
filename = "the_bumblezone_fabric-5.0.10+1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3735/704/the_bumblezone_fabric-5.0.10+1.18.2.jar"
hash-format = "sha1"
hash = "1f82485f1bb3044840f91bcb207ac5591f28f5df"

[update]
[update.curseforge]
file-id = 3735704
project-id = 363949
