name = "The Bumblezone (Fabric)"
filename = "the_bumblezone_fabric-4.3.5+1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3652/280/the_bumblezone_fabric-4.3.5+1.18.1.jar"
hash-format = "sha1"
hash = "47685e50f001f27feb64c2487330402f50ee6ff3"

[update]
[update.curseforge]
file-id = 3652280
project-id = 363949
