name = "This Rocks!"
filename = "rocks-1.6.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3747/170/rocks-1.6.0.jar"
hash-format = "sha1"
hash = "3cf589b998393d737e6fd669828178f98d4c9ef2"

[update]
[update.curseforge]
file-id = 3747170
project-id = 416283
