name = "Trade Cycling"
filename = "trade-cycling-fabric-1.18.2-1.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3669/602/trade-cycling-fabric-1.18.2-1.0.2.jar"
hash-format = "sha1"
hash = "75211e8fa6abe8f23d2e98d3c3b3deae567eecd0"

[update]
[update.curseforge]
file-id = 3669602
project-id = 570431
