name = "Trees Do Not Float"
filename = "tdnf-fabric-mc118-3.0.175.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3609/89/tdnf-fabric-mc118-3.0.175.jar"
hash-format = "sha1"
hash = "ac1de72837a3145d45ede2fd3b0f26c7a09c2450"

[update]
[update.curseforge]
file-id = 3609089
project-id = 323354
