name = "🪵 Twigs"
filename = "twigs-fabric-1.1.3-patch1+1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3735/923/twigs-fabric-1.1.3-patch1+1.18.2.jar"
hash-format = "sha1"
hash = "396d73769a99ed628b1aafaac3f53deb1f9aa309"

[update]
[update.curseforge]
file-id = 3735923
project-id = 496913
