name = "Universal Graves"
filename = "graves-2.0.0+1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3723/717/graves-2.0.0+1.18.2.jar"
hash-format = "sha1"
hash = "c4c751f64b34012e175b915060af4f5317260b85"

[update]
[update.curseforge]
file-id = 3723717
project-id = 497175
