name = "Urns"
filename = "urns-v1.0.1-mc1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3562/558/urns-v1.0.1-mc1.18.1.jar"
hash-format = "sha1"
hash = "ccff65d33d12b9b1f89974710c2e2ec552ba0388"

[update]
[update.curseforge]
file-id = 3562558
project-id = 491911
