name = "Villager Hats Mod"
filename = "villager-hats-mod-1.3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3648/78/villager-hats-mod-1.3.1.jar"
hash-format = "sha1"
hash = "52c0a6ef7c66918ec940ef75a7d8aa4341248d67"

[update]
[update.curseforge]
file-id = 3648078
project-id = 501456
