name = "Wither Cage Fix"
filename = "wither-cage-fix-1.0.11+MC1.18-1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3564/690/wither-cage-fix-1.0.11+MC1.18-1.18.1.jar"
hash-format = "sha1"
hash = "ab7740747be82358e98e0daa43a358ebb3c0146a"

[update]
[update.curseforge]
file-id = 3564690
project-id = 406807
